# Generated by Django 4.2.23 on 2025-07-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem_chain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemchainsession",
            name="engagement_times",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="problemchainsession",
            name="overall_session_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problemchainsession",
            name="problem_ratings",
            field=models.JSONField(default=list),
        ),
    ]
