# Generated by Django 4.2.23 on 2025-07-31 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problem_chain", "0002_problemchainsession_engagement_times_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityProblemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("problem_text", models.TextField()),
                ("difficulty_level", models.CharField(max_length=10)),
                ("total_attempts", models.IntegerField(default=0)),
                ("successful_completions", models.IntegerField(default=0)),
                ("total_rating_sum", models.IntegerField(default=0)),
                ("rating_count", models.IntegerField(default=0)),
                ("avg_engagement_time", models.FloatField(default=0.0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("avg_rating", models.FloatField(default=0.0)),
                (
                    "problem_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("user_preference_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "community_problem_metrics",
                "ordering": ["-avg_rating", "-success_rate"],
            },
        ),
        migrations.CreateModel(
            name="UserLearningPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "preferred_difficulty",
                    models.CharField(default="medium", max_length=10),
                ),
                ("avg_engagement_time", models.FloatField(default=0.0)),
                ("problem_preference_scores", models.JSONField(default=dict)),
                ("total_sessions", models.IntegerField(default=0)),
                ("avg_session_rating", models.FloatField(default=0.0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("learning_style", models.CharField(default="balanced", max_length=30)),
                ("confidence_level", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_pattern",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_learning_patterns",
            },
        ),
    ]
