# Generated by Django 4.2.23 on 2025-07-31 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problem_chain", "0003_communityproblemmetrics_userlearningpattern"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityLearningData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_text", models.TextField()),
                ("solution_text", models.TextField()),
                ("problem_hash", models.CharField(db_index=True, max_length=64)),
                ("user_rating", models.IntegerField()),
                ("overall_score", models.FloatField()),
                ("creativity_score", models.IntegerField(blank=True, null=True)),
                ("practicality_score", models.IntegerField(blank=True, null=True)),
                ("session_rating", models.IntegerField(blank=True, null=True)),
                ("difficulty", models.CharField(max_length=10)),
                ("round_number", models.IntegerField()),
                ("engagement_time", models.FloatField(blank=True, null=True)),
                (
                    "problem_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("success_pattern", models.JSONField(default=dict)),
                ("times_referenced", models.IntegerField(default=0)),
                ("avg_success_rate_when_used", models.FloatField(default=0.0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_learning_data",
                "ordering": ["-overall_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["difficulty", "overall_score"],
                        name="community_l_difficu_0d04b6_idx",
                    ),
                    models.Index(
                        fields=["problem_hash"], name="community_l_problem_e1a02e_idx"
                    ),
                    models.Index(
                        fields=["user_rating", "overall_score"],
                        name="community_l_user_ra_2d9782_idx",
                    ),
                ],
            },
        ),
    ]
