# Generated by Django 4.2.23 on 2025-07-29 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WordBridgeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("target_word", models.CharField(max_length=100)),
                ("start_word_options", models.JSONField(default=list)),
                ("selected_start_word", models.CharField(blank=True, max_length=100)),
                ("ai_solution_path", models.JSONField(default=list)),
                ("hints", models.JSONField(default=list)),
                ("submitted_words", models.JSONField(default=list)),
                ("hints_used", models.JSONField(default=list)),
                ("current_step", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("completed", "Tamamlandı"),
                            ("timeout", "Süre Doldu"),
                            ("abandoned", "Yarıda Bırakıldı"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("time_limit", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_score", models.JSONField(default=dict)),
                ("ai_evaluation", models.TextField(blank=True)),
                ("alternative_solutions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "word_bridge_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
