# Generated by Django 4.2.23 on 2025-07-27 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemorySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("selected_topic", models.CharField(blank=True, max_length=100)),
                ("topic_options", models.JSONField(default=list)),
                ("original_text", models.TextField(blank=True)),
                ("text_keywords", models.JSONField(default=list)),
                ("user_recall", models.TextField(blank=True)),
                ("user_keywords", models.JSONField(default=list)),
                (
                    "synthesis_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("simplify", "Basitleştirme"),
                            ("connect", "Bağlantı Kurma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("synthesis_text", models.TextField(blank=True)),
                ("scores", models.JSONField(default=dict)),
                ("reading_time", models.IntegerField(default=0)),
                ("ai_feedback", models.TextField(blank=True)),
                ("alternative_keywords", models.JSONField(default=list)),
            ],
            options={
                "db_table": "memory_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
