# Generated by Django 4.2.23 on 2025-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memorysession",
            old_name="synthesis_text",
            new_name="ai_answer",
        ),
        migrations.RemoveField(
            model_name="memorysession",
            name="synthesis_type",
        ),
        migrations.AddField(
            model_name="memorysession",
            name="question_is_relevant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memorysession",
            name="user_question",
            field=models.TextField(blank=True),
        ),
    ]
