# Generated by Django 4.2.23 on 2025-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="average_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="best_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="memory_exercises_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_exercise_type",
            field=models.CharField(default="memory", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="problem_chain_exercises_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supabase_synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supabase_user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_time_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="word_bridge_exercises_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_difficulty",
            field=models.CharField(
                choices=[("easy", "Kolay"), ("medium", "Orta"), ("hard", "Zor")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
    ]
