# Generated by Django 4.2.23 on 2025-07-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userexerciseactivity_dailyuserstats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="favorite_difficulty",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_exercise_type",
        ),
    ]
