# Generated by Django 4.2.23 on 2025-07-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_wordbridgesession_delete_wordbridgeexercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problemchainsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wordbridgesession",
            name="user",
        ),
        migrations.DeleteModel(
            name="MemoryExercise",
        ),
        migrations.DeleteModel(
            name="ProblemChainSession",
        ),
        migrations.DeleteModel(
            name="WordBridgeSession",
        ),
    ]
