# Generated by Django 4.2.23 on 2025-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativityexercise",
            name="character",
            field=models.CharField(
                blank=True,
                help_text="Orta ve Zor seviyeler için karakter tanımı",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creativityexercise",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Kolay"), ("medium", "Orta"), ("hard", "Zor")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="creativityexercise",
            name="setting",
            field=models.CharField(
                blank=True,
                help_text="Zor seviye için mekan tanımı",
                max_length=255,
                null=True,
            ),
        ),
    ]
